<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>siebel</string>
	</array>
	<key>name</key>
	<string>Easy Siebel</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>(?i:\b(IIF|BCHasRows)\b)</string>
			<key>name</key>
			<string>keyword.control.siebel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>=|&gt;=|&lt;|&gt;|&lt;|&lt;&gt;|\+|-|\*|\^|&amp;|\b(?i:(AND|OR|IS|NOT|NULL)\b)</string>
			<key>name</key>
			<string>keyword.operator.siebel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:\b(LookupValue|LookupName|FieldValue)\b)</string>
			<key>name</key>
			<string>constant.function.siebel</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.begin</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.end</string>
				</dict>
			</dict>
			<key>name</key>
			<string>support.bracket.round.siebel</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.siebel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\(</string>
			<key>name</key>
			<string>markup.bold.round.bracket.begin</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\)</string>
			<key>name</key>
			<string>markup.bold.round.bracket.begin</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.siebel</string>
	<key>uuid</key>
	<string>06858447-018d-4560-a2ef-819d206ba054</string>
</dict>
</plist>
